-- Clock In: schema `app` (ARCHITECTURE §4, §5).
--
-- The tables live in `app`, which is NOT in the Data API's exposed schemas.
-- RLS is on with zero policies, and `anon` / `authenticated` get no
-- privileges at all. Every read and write goes through the SECURITY DEFINER
-- RPC functions in `public` (next migration).

create extension if not exists pgcrypto with schema extensions;

create schema if not exists app;

-- Lock the schema down before anything is created in it.
revoke all on schema app from public, anon, authenticated;
alter default privileges in schema app revoke all on tables from public, anon, authenticated;
alter default privileges in schema app revoke all on sequences from public, anon, authenticated;
alter default privileges in schema app revoke all on functions from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table app.staff (
    id          uuid primary key default gen_random_uuid(),
    first_name  text not null check (char_length(first_name) between 1 and 40),
    last_name   text not null check (char_length(last_name) between 1 and 40),
    removed_at  timestamptz,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- Weekly template. `weekday` is a business day, Monday = 1 … Sunday = 7.
create table app.schedule_blocks (
    id          uuid primary key default gen_random_uuid(),
    staff_id    uuid not null references app.staff (id) on delete cascade,
    weekday     smallint not null check (weekday between 1 and 7),
    start_time  time(0) not null,
    end_time    time(0) not null,
    check (start_time <> end_time),
    check (date_trunc('minute', start_time) = start_time),
    check (date_trunc('minute', end_time) = end_time)
);
create index schedule_blocks_staff_idx on app.schedule_blocks (staff_id);

-- One-off change for one person on one business date (SPEC §4.3).
create table app.overrides (
    id             uuid primary key default gen_random_uuid(),
    staff_id       uuid not null references app.staff (id) on delete cascade,
    business_date  date not null,
    kind           text not null check (kind in ('off', 'replace')),
    created_at     timestamptz not null default now(),
    unique (staff_id, business_date)
);
create index overrides_date_idx on app.overrides (business_date);

create table app.override_blocks (
    id           uuid primary key default gen_random_uuid(),
    override_id  uuid not null references app.overrides (id) on delete cascade,
    start_time   time(0) not null,
    end_time     time(0) not null,
    check (start_time <> end_time),
    check (date_trunc('minute', start_time) = start_time),
    check (date_trunc('minute', end_time) = end_time)
);
create index override_blocks_override_idx on app.override_blocks (override_id);

-- Singleton (SPEC §4.4). `quit_code` is null until `admin_initialize`.
create table app.settings (
    id                   boolean primary key default true check (id),
    checkin_offset_min   integer not null default 0 check (checkin_offset_min between -60 and 30),
    checkout_offset_min  integer not null default 0 check (checkout_offset_min between -60 and 30),
    rollover             time(0) not null default '05:00'
                         check (rollover between '00:00' and '08:00'
                                and date_trunc('minute', rollover) = rollover),
    autostart            boolean not null default true,
    quit_code            text check (quit_code ~ '^[0-9]{4}$')
);

create table app.devices (
    id            uuid primary key default gen_random_uuid(),
    name          text not null check (char_length(name) between 1 and 60),
    platform      text not null check (platform in ('windows', 'android')),
    -- SHA-256 of the device secret; the secret itself is never stored.
    secret_hash   bytea not null unique check (octet_length(secret_hash) = 32),
    created_at    timestamptz not null default now(),
    last_seen_at  timestamptz,
    revoked_at    timestamptz
);

-- `id` is generated by the client, which makes inserts idempotent.
create table app.marks (
    id               uuid primary key,
    staff_id         uuid not null references app.staff (id),
    source_block_id  uuid not null,
    business_date    date not null,
    kind             text not null check (kind in ('in', 'out')),
    marked_at        timestamptz not null default now(),
    device_id        uuid references app.devices (id) on delete set null,
    voided_at        timestamptz
);
-- At most one live mark per block occurrence and kind: a second device
-- marking the same person gets the existing mark back.
create unique index marks_one_live_idx
    on app.marks (staff_id, source_block_id, business_date, kind)
    where voided_at is null;
create index marks_date_idx on app.marks (business_date);

-- Singleton. bcrypt hash of the normalised passphrase, plus the lockout
-- shared by `admin_login`, `pair_device` and `change_passphrase`.
create table app.auth_state (
    id               boolean primary key default true check (id),
    passphrase_hash  text,
    failed_count     integer not null default 0 check (failed_count >= 0),
    locked_until     timestamptz
);

create table app.admin_sessions (
    token_hash  bytea primary key check (octet_length(token_hash) = 32),
    device_id   uuid not null references app.devices (id) on delete cascade,
    expires_at  timestamptz not null
);

-- The materialised alarm plan, computed by `clockin-core` on a device.
create table app.alarm_plan (
    item_id          text primary key check (item_id ~ '^[0-9a-f]{32}$'),
    fires_at         timestamptz not null,
    kind             text not null check (kind in ('in', 'out')),
    staff_id         uuid not null,
    display_name     text not null check (char_length(display_name) between 1 and 100),
    business_date    date not null,
    source_block_id  uuid not null
);
create index alarm_plan_fires_idx on app.alarm_plan (fires_at);

-- Singleton.
create table app.meta (
    id                   boolean primary key default true check (id),
    -- Bumped by changes to staff, blocks, overrides and settings.
    config_version       bigint not null default 0,
    -- Bumped by every change a device should refetch for.
    data_version         bigint not null default 0,
    -- `config_version` the uploaded plan was computed from.
    plan_config_version  bigint not null default 0,
    plan_horizon_end     timestamptz
);

insert into app.settings default values;
insert into app.auth_state default values;
insert into app.meta default values;

-- ---------------------------------------------------------------------------
-- Version triggers
-- ---------------------------------------------------------------------------

create function app.bump_config_version() returns trigger
language plpgsql
set search_path = ''
as $$
begin
    update app.meta
       set config_version = config_version + 1,
           data_version = data_version + 1
     where id;
    return null;
end;
$$;

create function app.bump_data_version() returns trigger
language plpgsql
set search_path = ''
as $$
begin
    update app.meta set data_version = data_version + 1 where id;
    return null;
end;
$$;

create trigger staff_bump after insert or update or delete on app.staff
    for each row execute function app.bump_config_version();
create trigger schedule_blocks_bump after insert or update or delete on app.schedule_blocks
    for each row execute function app.bump_config_version();
create trigger overrides_bump after insert or update or delete on app.overrides
    for each row execute function app.bump_config_version();
create trigger override_blocks_bump after insert or update or delete on app.override_blocks
    for each row execute function app.bump_config_version();
create trigger settings_bump after update on app.settings
    for each row execute function app.bump_config_version();
create trigger marks_bump after insert or update or delete on app.marks
    for each row execute function app.bump_data_version();
-- `last_seen_at` updates (every minute per device) are not data changes.
create trigger devices_bump after insert or delete or update of name, platform, revoked_at on app.devices
    for each row execute function app.bump_data_version();

-- ---------------------------------------------------------------------------
-- RLS on, zero policies (defence in depth); no privileges for API roles.
-- ---------------------------------------------------------------------------

alter table app.staff           enable row level security;
alter table app.schedule_blocks enable row level security;
alter table app.overrides       enable row level security;
alter table app.override_blocks enable row level security;
alter table app.settings        enable row level security;
alter table app.devices         enable row level security;
alter table app.marks           enable row level security;
alter table app.auth_state      enable row level security;
alter table app.admin_sessions  enable row level security;
alter table app.alarm_plan      enable row level security;
alter table app.meta            enable row level security;

revoke all on all tables in schema app from public, anon, authenticated;
revoke all on all sequences in schema app from public, anon, authenticated;
revoke all on all functions in schema app from public, anon, authenticated;
